# Generated by Django 2.1.5 on 2019-01-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_contactform_listing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='listing_id',
            field=models.IntegerField(),
        ),
    ]
