# Generated by Django 2.1.7 on 2019-06-24 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
