# Generated by Django 2.1.5 on 2019-02-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
