# Generated by Django 2.1.7 on 2019-03-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comments',
            field=models.CharField(default='heloo', max_length=500),
        ),
    ]
