# Generated by Django 2.1.7 on 2019-03-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='email',
            field=models.CharField(default='email', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='comments',
            field=models.CharField(default='comment', max_length=500),
        ),
    ]
